### PR TITLE
add capability of parsing styles which is not about font

### PR DESCRIPTION
**Pull request by freedomsean**
Thanks, it is a useful plugin, but when I try to use this plugin to download Material Icons, it download the part of font-family only, so I  modified regex and changed the template of output. 
Now, It will have capability of parsing styles which is not about font in google font.

### CODE REVIEW

**Comment by luckyraul** [comment]
thanks

**Comment by luckyraul** [comment]
@freedomsean 

otherCss is writing for every font in list, this is not correct

try with 

```
Material+Icons
Roboto:500,500italic&subset=greek
```

**Comment by freedomsean** [comment]
@luckyraul 

Hi, I think that I do not explain clearly enough, due to my poor English.
When I want to download "Material+Icons", I found that it will contains not only font-family but also "otherCSS"

The following is the style of Material Icon. ".material-icons" won't be added into "bundle.css" which contain all fonts , because you used a template to generate the font files.

I added "otherCSS" and change the template, in order to make "bundle.css" have all styles which contains in the original font style.

In other way, I think if the "otherCSS" can be bundle into another files such as "otherCSS.bundle" will be cleaner, but I think most of users(like me ) do not want to know what is it in this bundle file, they only want to make the style correct.

`/\* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url(http://fonts.gstatic.com/s/materialicons/v18/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}`

**Comment by luckyraul** [comment]
Just try your code with font.list with such a content 

```
Material+Icons
Roboto:500,500italic&subset=greek
```

=)

**Comment by freedomsean** [comment]
@luckyraul , I have tried. When I use the above config and this package, it can not render material icons correctly.

**Comment by luckyraul** [comment]
@freedomsean 

```
Material+Icons
Roboto:500,500italic&subset=greek
```

in your code https://github.com/freedomsean/gulp-google-fonts-base64-css. You will see the bad part of your's pull requests.

**Pull request merged**
